### ISSUE TITLE
Compatibility with other S3-compliant solutions (e.g. DigitalOcean Spaces)

### ISSUE THREAD

**Issue by brendanbond** [gatsby-uc/gatsby-source-s3#100]
Hi Robin, thanks for developing and maintaining this plugin. Though I'm not confident enough in my ability to create a robust and testable PR for this, I think it'd be fairly easy to change the way the plugin conducts AWS auth in order to make it compatible with other S3-compliant solutions such as DigitalOcean spaces.

The current authentication process involves the AWS config object:
```
const { aws: awsConfig, buckets } = pluginOptions;
AWS.config.update(awsConfig);
  const s3 = new AWS.S3();
```

To expand this plugin's compatibility with other S3-compliant solutions, couldn't we add a configurable endpoint to the plugin options (one that still defaults to an S3 endpoint and uses the region property) and perhaps just pass the config object to the s3 constructor?
```
const someOtherS3CompliantEndpoint = `https://${region}.digitaloceanspace.com`; // e.g.
const s3 = new AWS.S3({
    endpoint: someOtherS3CompliantEndpoint,
    accessKeyId: process.env.CLIENT_KEY,
    secretAccessKey: process.env.CLIENT_SECRET
});
```

**Comment by brendanbond** [comment]
After thinking about it for 20 minutes, this is a total copout - I'm going to try my hand at a PR! Hopefully I can learn stuff along the way

**Comment by robinmetral** [comment]
Hey @brendanbond, sorry for my late reply, I was away for a bit 🙂 

I think that this is a great idea! I'll reopen the issue to keep track of it, if you don't mind.

I'm not very familiar with the differences between S3 and S3-compliant solutions, but I'd be more than happy to review and help test a PR. Is this still something you're interested to contribute? Anything I can do to help?

**Comment by moonmeister** [comment]
Thanks for your interest in `gatsby-source-s3`. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or Join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
